version: "3.5"

services:
  app:
    build:
      context: ./
    ports:
      - 3000:3000/tcp
      - 3001:3001/tcp
    command: bash /go/src/entrypoint.sh
  redis:
    image: redis
  postgres:
    image: postgres
    container_name: postgres-hex
    volumes:
      - ./database/psql/init.sql:/docker-entrypoint-initdb.d/init.sql
